spring.application.name=athletiquest-api

# bdd
spring.datasource.url=jdbc:postgresql://localhost:5432/athletiquest
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=athletiquest
spring.datasource.password=athletiquest

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.data.mongodb.uri=mongodb://athletiquest:athletiquest@localhost:27017/athletiquest?authSource=admin
spring.data.mongodb.auto-index-creation=true

retrieve-stadiums-on-start=false
retrieve-stadiums-on-start.if-days-since-last-update=7
retrieve-stadiums-on-start.if-collection-empty=true

api-gouv.stadiums.request-path=https://equipements.sports.gouv.fr/api/explore/v2.1/catalog/datasets/data-es/records?select=equip_numero,inst_nom,equip_x,equip_y,inst_cp,new_name,new_code,equip_type_name,equip_acc_libre&where=(equip_type_code LIKE "1001" OR equip_type_code LIKE "1002" OR equip_type_code LIKE "1003" OR equip_type_code LIKE "1004" OR equip_type_code LIKE "1005") AND equip_ouv_public_bool="true" AND equip_coordonnees IS NOT NULL&order_by=equip_numero&limit=100&offset={0}
