# bdd
spring.datasource.url=jdbc:mysql://mysql_athletiquest:3306/athletiquest
spring.datasource.username=athletiquest
spring.datasource.password=athletiquest

spring.data.mongodb.uri=mongodb://athletiquest:athletiquest@localhost:27017/athletiquest

