name: Build & Push to GHCR

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
#  run_tests:
#    runs-on: ubuntu-22.04
#    steps:
#      - name: Build tests
#        uses: actions/ma
  build_and_push:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract image
        id: extract
        run: |
          IMAGE_NAME="ghcr.io/$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')"
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Build Docker
        run: |
          docker build -f backend/Dockerfile -t ${{ steps.extract.outputs.image_name }}:latest .

      - name: Push Docker image
        run: |
          docker push ${{ steps.extract.outputs.image_name }}:latest
