name: Build & Push to GHCR

on:
  pull_request

permissions:
  contents: read
  packages: write

jobs:
  build_and_test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Prepare
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'adopt'

      - name: Set up the Maven dependencies caching
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install Maven dependencies
        run: mvn install

      - name: Run tests
        run: mvn --batch-mode --update-snapshots verify
